name: testing

on:
  pull_request:
    branches:
    - master

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Cache composer
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    - name: Run api tests
      run: |-
        composer install
        echo "php-cs-fixer pre commit hook start"
        PHP_CS_FIXER="/var/www/vendor/php-cs-fixer"
        PHP_CS_CONFIG=".php-cs-fixer.dist.php"
        CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.php')

        if [ -n "$CHANGED_FILES" ]; then
          $PHP_CS_FIXER fix --config "$PHP_CS_CONFIG" $CHANGED_FILES;
          git add $CHANGED_FILES;
        fi
        echo "php-cs-fixer pre commit hook finish"
    
